apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sandbox.root.fyre-dev
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-gitops
    server: 'https://kubernetes.default.svc'
  project: "mas"
  source:
    path: root-applications/ibm-mas-account-root
    repoURL: https://github.com/tomklapiscak/gitops-sandbox
    targetRevision: "deleteprotection"
    helm:
      values: |
          account:
            id: fyre-dev

          generator:
            repo_url: "https://github.ibm.comcom/maximoappsuite/gitops-envs"
            revision: "deleteprotection"

          source:
            repo_url: "https://github.com/tomklapiscak/gitops-sandbox"
            revision: "deleteprotection"
          
          argo:
            namespace: "openshift-gitops"
            projects:
              rootapps: mas
              apps: mas

          auto_delete: false
    
  syncPolicy:
    syncOptions:
      - CreateNamespace=false