---
kind: Secret
apiVersion: v1
metadata:
  name: sandbox-postdelete-secret
  namespace: default
  annotations:
    argocd.argoproj.io/hook: PostDelete
stringData:
  hello: "world"
type: Opaque


---
apiVersion: batch/v1
kind: Job
metadata:
  name: sandbox-postdelete-job
  namespace: default
  annotations:
    argocd.argoproj.io/hook: PostDelete
spec:
  template:
    spec:
      containers:
        - name: run
          image: quay.io/ibmmas/cli:10.1.0-pre.gitops
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 200m
              memory: 512Mi
            requests:
              cpu: 10m
              memory: 64Mi

          command:
            - /bin/sh
            - -c
            - |

              set -e
              for i in {1..10}; do echo "Iteration $i"; sleep 10; done


      restartPolicy: Never
      serviceAccountName: default

  backoffLimit: 4