
---
# IBM Maximo Application Suite Account Root Application Set
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: mascore2816.cluster-appset.{{ .Values.account.id }}
  namespace: {{ .Values.argo.namespace }}
  labels:
    environment: '{{ .Values.account.id }}'
  annotations:
    argocd.argoproj.io/sync-wave: "000"
spec:
  goTemplate: true
  generators:
    - merge:
        mergeKeys:
          # Would love to use ".path.path" here to merge the configs together
          # but this is not possible currently with goTemplate: true - see https://github.com/argoproj/argo-cd/issues/12836
          # (and we really want goTemplate: true so we can dump the entire config file into HELM_VALUES using toPrettyJson)
          # instead, we are forced to explicitly provide a merge key in all of our config files to make them line up
          - 'merge-key'
        generators:
          # This is the "base" generator, it *must* be first in the list
          - git:
              repoURL: "{{ .Values.generator.repo_url }}"
              revision: "{{ .Values.generator.revision }}"
              files:
              - path: "{{ .Values.account.id }}/*/ibm-mas-cluster-base.yaml"
          - git:
              repoURL: "{{ .Values.generator.repo_url }}"
              revision: "{{ .Values.generator.revision }}"
              files:
              - path: "{{ .Values.account.id }}/*/cluster-dummy.yaml"
  template:
    metadata:
      name: "mascore2816.cluster.{{ `{{.cluster.id}}` }}"
      labels:
        environment: '{{ .Values.account.id }}'
        region: '{{ `{{ .region.id }}` }}'
        cluster: '{{ `{{ .cluster.id }}` }}'
{{- if .Values.custom_labels }}
{{ .Values.custom_labels | toYaml | indent 8 }}
{{- end }}
      annotations:
        healthCheckTimeout: "1800"
    spec:
      project: "{{ .Values.argo.projects.rootapps }}"
      source:
          repoURL: "{{ .Values.source.repo_url }}"
          targetRevision: "{{ .Values.source.revision }}"
          path: root-applications/ibm-mas-cluster-root
          helm:
            releaseName: clusterappset
            values: "{{ `{{ toYaml . }}` }}"
            parameters:
              - name: "generator.repo_url"
                value: "{{ .Values.generator.repo_url }}"
              - name: "generator.revision"
                value: "{{ .Values.generator.revision }}"
              - name: "source.revision"
                value: "{{ .Values.source.revision }}"
              - name: "source.repo_url"
                value: "{{ .Values.source.repo_url }}"
              - name: argo.namespace
                value: "{{ .Values.argo.namespace }}"
              - name: argo.projects.rootapps
                value: "{{ .Values.argo.projects.rootapps }}"
              - name: argo.projects.apps
                value: "{{ .Values.argo.projects.apps }}"
              - name: avp.name
                value: "{{ .Values.avp.name }}"
              - name: avp.secret
                value: "{{ .Values.avp.secret }}"
              - name: avp.values_varname
                value: "{{ .Values.avp.values_varname }}"

              - name: prune
                value: "{{ .Values.prune }}"
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: {{ .Values.argo.namespace }}
      syncPolicy:
        automated:
          prune: {{ .Values.prune }}
          selfHeal: true
        syncOptions:
          - CreateNamespace=false
          - RespectIgnoreDifferences=true
