---


avp:
  name: "argocd-vault-plugin-helm"
  secret: ""
  values_varname: "HELM_VALUES"



source:
  repo_url: "https://github.com/ibm-mas/gitops"
  revision: "poc"

# Customers will definitely need to customise this (our gitops-envs/mas-dev repos are private),
# So deliberately not specifying defaults here; we want charts to refuse to render if these are not specified
# Both of these correspond to requirement arguments of the gitops-bootstrap CLI function (--github-url and --github-revision)
# generator:
#   repo_url: ""
#   revision: ""

# These defaults align with the ArgoCD worker setup by gitops-bootstrap
# (openshift-gitops with a single ArgoCD project "mas")
argo:
  namespace: "openshift-gitops"
  projects:
    rootapps: "mas"
    apps: "mas"
